blank_issues_enabled: false
contact_links:
  - name: nanovna-users groups.io group
    url: https://groups.io/g/nanovna-users/
    about: Please ask any questions about using the NanoVNA or NanoVNA-Saver on this mailing list.
